using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;

namespace StructuredProductMonograph.Models
{
    public enum CodeEnum
    {
        TitlePage = 450,
        TitleBlock = 460,
        PharmaceuticalStandard = 110,
        TherapeuticClassification = 120,
        DatePreparation = 150,
        DateRevision = 160,
        SubmissionControlNumber = 170,
        Footnote = 440,
        TableOfContents = 500,
        PartIPage = 20,
        SchedulingSymbol = 60,
        SummaryProductInformation =180,
        IndicationsAndClinicalUse = 190,
        PatientSubsets = 19010,
        Geriatrics = 1901010,
        Pediatrics = 1901020,
        Contradictions = 200,
        WarningsAndPrecautions = 210,
        WarningsAndPrecautionsGeneral = 21010,
        CarcinogenesisAndMutagenesis = 21020,
        Cardiovascular = 21030,
        SpecialPopulations = 210210,
        PregnantWomen = 21021010,
        NursingWomen = 21021020,
        SpecialPopulationsPediatrics = 21021030,
        SpecialPopulationsGeriatrics = 21021040,
        SpecialPopulationsMisc = 210220,
        MonitoringAndLaboratoryTests = 210230,
        AdverseReactions = 220,
        AdverseDrugReactionOverview = 22010,
        ClinicalTrialAdverseDrugReactions = 22020,
        LessCommonClinicalTrialAdverseDrugReactions = 22030,
        AbnormalHematologicAndClinicalChemistryFindings = 22040,
        PostMarketAdverseDrugReactions = 22050,
        DrugInteractions = 230,
        DrugInteractionsOverview = 23080,
        DrugDrugInteractions = 23010,
        DrugFoodInteractions = 23020,
        DrugHerbInteractions = 23030,
        DrugLaboratoryTestInteractions = 23040,
        DrugLifestyleInteractions = 23050,
        DosageAndAdministration = 240,
        DosingConsiderations = 24010,
        RecommendedDoseAndDosageAdjustment = 24020,
        DosageAdministrationMissedDose = 24030,
        Administration = 24040,
        Reconstitution = 24050,
        OralSolutions = 2405010,
        ParenteralProducts = 2405020,
        Overdosage = 250,
        ActionAndClinicalPharmacology = 260,
        MechanismOfAction = 26010,
        Pharmacodynamics = 26020,
        Pharmacokinetics = 26030,
        Absorption = 2603010,
        Distribution = 2603020,
        Metabolism = 2603030,
        Excretion = 2603040,
        SpecialPopulationsAndConditions = 2603050,
        ActionAndClinicalPediatrics = 260305010,
        ActionAndClinicalGeriatrics = 260305020,
        Gender = 260305030,
        Race = 260305040,
        HepaticInsufficiency = 260305050,
        RenalInsufficiency = 260305060,
        GeneticPolymorphism = 260305070,
        StorageandStability = 270,
        SpecialHandlingInstructions = 280,
        DosageFormsCompositionandPackaging = 290,
        PartIIPage = 30,
        PharmaceuticalInformation = 300,
        DrugSubstance = 30010,
        DrugProperName = 3001010,
        ChemicalName = 3001020,
        MolecularFormulaAndMolecularMass = 3001030,
        StructuralformulaIncludingrelative = 3001040,
        PhysicochemicalProperties = 3001050,
        ClinicalTrials = 310,
        EfficacyandSafetyStudies = 31010,
        StudyDemographicsAndTrialDesign = 3101010,
        StudyResults = 3101020,
        PivotalComparativeBioavailabilityStudies = 31020,
        DetailedPharmacology = 320,
        Microbiology = 330,
        Toxicology = 340,
        References = 350,
        PartIIIPage = 40,
        General = 480,
        OpeningDisclaimer = 490,
        AboutThisMedication = 360,
        WhatTheMedicationIsUsedFor =36010,
        WhatItDoes = 36020,
        WhenItShouldNotBeUsed = 36030,
        WhatTheMedicinalIngredientIs = 36040,
        WhatTheImportantNonmedicinalIngredientsAre = 36050,
        WhatDosageFormsItComesIn = 36060,
        WarningAndPrecaution = 370,
        InteractionsWithThisMedication = 380,
        SideEffectsandwhatToDoAboutThem = 400,
        ProperUseOfThisMedication =390,
        UsualDose = 39010,
        Overdose = 39020,
        MissedDose = 39030,
        HowToStoreIt = 410,
        ReportingSuspectedSideEffects = 420,
        MoreInformation = 430,
        PartIIIRevisionDate = 470
    }

    public class CodeType
    {
        public string Code { get; set; }
        public string DisplayName { get; set; }
    }

    public static class CodeCollection
    {
        public  static IDictionary<CodeEnum, CodeType> codes = new Dictionary<CodeEnum, CodeType>()
        {
            {CodeEnum.TitlePage, new CodeType {Code="450", DisplayName="Title Page"}},
            {CodeEnum.TitleBlock, new CodeType {Code="460", DisplayName="Title Block"}},
            {CodeEnum.PharmaceuticalStandard, new CodeType {Code="110", DisplayName="Pharmaceutical Standard"}},
            {CodeEnum.TherapeuticClassification, new CodeType {Code="120", DisplayName="Therapeutic Classification"}},
            {CodeEnum.DatePreparation, new CodeType {Code="150", DisplayName="Date of Preparation"}},
            {CodeEnum.DateRevision, new CodeType {Code="160", DisplayName="Date of Revision"}},
            {CodeEnum.SubmissionControlNumber, new CodeType {Code="170", DisplayName="Submission Control Number"}},
            {CodeEnum.Footnote, new CodeType {Code="440", DisplayName="Footnote"}},
            {CodeEnum.TableOfContents, new CodeType {Code="500", DisplayName="Table Of Contents"}},
            {CodeEnum.PartIPage, new CodeType {Code="20", DisplayName="Part I: Health Professional Information"}},
            {CodeEnum.SummaryProductInformation, new CodeType {Code="180", DisplayName="Summary Product Information"}},
            {CodeEnum.Contradictions, new CodeType {Code="200", DisplayName="Contradictions"}},
            {CodeEnum.AdverseReactions, new CodeType {Code="220", DisplayName="Adverse Reactions"}},
            {CodeEnum.AdverseDrugReactionOverview, new CodeType {Code="220-10", DisplayName="Adverse Drug Reaction (ADR) Overview"}},
            {CodeEnum.ClinicalTrialAdverseDrugReactions, new CodeType {Code="220-20", DisplayName="Clinical Trial Adverse Drug Reactions"}},
            {CodeEnum.LessCommonClinicalTrialAdverseDrugReactions, new CodeType {Code="220-30", DisplayName="Less Common Clinical Trial Adverse Drug Reactions"}},
            {CodeEnum.AbnormalHematologicAndClinicalChemistryFindings, new CodeType {Code="220-40", DisplayName="Abnormal Hematologic And Clinical Chemistry "}},
            {CodeEnum.PostMarketAdverseDrugReactions, new CodeType {Code="220-50", DisplayName="Post-Market Adverse Drug Reactions"}},
            {CodeEnum.DrugInteractions, new CodeType {Code="230", DisplayName="Drug Interactions"}},
            {CodeEnum.DrugInteractionsOverview, new CodeType {Code="230-80", DisplayName="Overview"}},
            {CodeEnum.DrugDrugInteractions, new CodeType {Code="230-10", DisplayName="Drug-Drug Interactions"}},
            {CodeEnum.DrugFoodInteractions, new CodeType {Code="230-20", DisplayName="Drug-Food Interactions"}},
            {CodeEnum.DrugHerbInteractions, new CodeType {Code="230-30", DisplayName="Drug-Herb Interactions"}},
            {CodeEnum.DrugLaboratoryTestInteractions, new CodeType {Code="230-40", DisplayName="Drug-Laboratory Test Interactions"}},
            {CodeEnum.DrugLifestyleInteractions, new CodeType {Code="230-50", DisplayName="Drug-Lifestyle Interactions"}},
            {CodeEnum.DosageAndAdministration, new CodeType {Code="240",       DisplayName="Dosage And Administration"}},
            {CodeEnum.DosingConsiderations, new CodeType {Code="240-10",    DisplayName="Dosing Considerations"}},
            {CodeEnum.RecommendedDoseAndDosageAdjustment, new CodeType {Code="240-20",    DisplayName="Recommended Dose And Dosage Adjustment"}},
            {CodeEnum.DosageAdministrationMissedDose, new CodeType {Code="240-30",    DisplayName="Missed Dose"}},
            {CodeEnum.Administration, new CodeType {Code="240-40",    DisplayName="Administration"}},
            {CodeEnum.Reconstitution, new CodeType {Code="240-50",    DisplayName="Reconstitution"}},
            {CodeEnum.OralSolutions, new CodeType {Code="240-50-10", DisplayName="Oral Solutions"}},
            {CodeEnum.ParenteralProducts, new CodeType {Code="240-50-20", DisplayName="Parenteral Products"}},
            {CodeEnum.Overdosage, new CodeType {Code="250", DisplayName="Overdosage"}},
            {CodeEnum.ActionAndClinicalPharmacology, new CodeType{Code= "260", DisplayName="Action And Clinical Pharmacology" }},
            {CodeEnum.MechanismOfAction, new CodeType{Code= "260-10", DisplayName="Mechanism Of Action" }},
            {CodeEnum.Pharmacodynamics, new CodeType{Code= "260-20", DisplayName="Pharmacodynamics" }},
            {CodeEnum.Pharmacokinetics, new CodeType{Code= "260-30", DisplayName="Pharmacokinetics" }},
            {CodeEnum.Absorption, new CodeType{Code= "260-30-10", DisplayName="Absorption" }},
            {CodeEnum.Distribution, new CodeType{Code= "260-30-20", DisplayName="Distribution" }},
            {CodeEnum.Metabolism, new CodeType{Code= "260-30-30", DisplayName="Metabolism" }},
            {CodeEnum.Excretion, new CodeType{Code= "260-30-40", DisplayName="Excretion" }},
            {CodeEnum.SpecialPopulationsAndConditions, new CodeType{Code= "260-30-50", DisplayName="Special Populations And Conditions" }},
            {CodeEnum.ActionAndClinicalPediatrics, new CodeType{Code= "260-30-50-10", DisplayName="Pediatrics" }},
            {CodeEnum.ActionAndClinicalGeriatrics, new CodeType{Code= "260-30-50-20", DisplayName="Geriatrics" }},
            {CodeEnum.Gender, new CodeType{Code= "260-30-50-30", DisplayName="Gender" }},
            {CodeEnum.Race, new CodeType{Code= "260-30-50-40", DisplayName="Race" }},
            {CodeEnum.HepaticInsufficiency, new CodeType{Code= "260-30-50-50", DisplayName="Hepatic Insufficiency" }},
            {CodeEnum.RenalInsufficiency, new CodeType{Code= "260-30-50-60", DisplayName="Renal Insufficiency" }},
            {CodeEnum.GeneticPolymorphism, new CodeType{Code= "260-30-50-70", DisplayName="Genetic Polymorphism" }},
            {CodeEnum.StorageandStability, new CodeType {Code="270", DisplayName="Storage and Stability"}},
            {CodeEnum.SpecialHandlingInstructions, new CodeType {Code="280", DisplayName="Special Handling Instructions"}},
            {CodeEnum.DosageFormsCompositionandPackaging, new CodeType {Code="290", DisplayName="Dosage Forms, Composition and Packaging"}},
            {CodeEnum.PartIIPage, new CodeType {Code="30", DisplayName="Part II: Scientific Information"}},
            {CodeEnum.PharmaceuticalInformation, new CodeType { Code="300		", DisplayName="Pharmaceutical Information"}},
            {CodeEnum.DrugSubstance, new CodeType { Code="300-10	", DisplayName="Drug Substance"}},
            {CodeEnum.DrugProperName, new CodeType { Code="300-10-10", DisplayName="Proper Name"}},
            {CodeEnum.ChemicalName, new CodeType { Code="300-10-20", DisplayName="Chemical Name"}},
            {CodeEnum.MolecularFormulaAndMolecularMass, new CodeType { Code="300-10-30", DisplayName="Molecular Formula And Molecular Mass"}},
            {CodeEnum.StructuralformulaIncludingrelative, new CodeType { Code="300-10-40", DisplayName="Structural formula, including relative and absolute stereochemistry"}},
            {CodeEnum.PhysicochemicalProperties, new CodeType { Code="300-10-50", DisplayName="Physicochemical Properties"}},
            {CodeEnum.ClinicalTrials, new CodeType {Code ="310", DisplayName ="Clinical Trials"}},
            {CodeEnum.EfficacyandSafetyStudies  , new CodeType {Code ="310-10", DisplayName ="Efficacy and Safety Studies  "}},
            {CodeEnum.StudyDemographicsAndTrialDesign, new CodeType {Code ="310-10-10", DisplayName ="Study Demographics And Trial Design"}},
            {CodeEnum.StudyResults, new CodeType {Code ="310-10-20", DisplayName ="Study Results"}},
            {CodeEnum.PivotalComparativeBioavailabilityStudies, new CodeType {Code ="310-20", DisplayName ="Pivotal Comparative Bioavailability Studies"}},
            {CodeEnum.DetailedPharmacology, new CodeType {Code="320", DisplayName="Detailed Pharmacology"}},
            {CodeEnum.Microbiology, new CodeType {Code="330", DisplayName="Microbiology"}},
            {CodeEnum.Toxicology, new CodeType {Code="340", DisplayName="Toxicology"}},
            {CodeEnum.References, new CodeType {Code="350", DisplayName="References"}},
            {CodeEnum.PartIIIPage, new CodeType {Code="40", DisplayName="Part III: Consumer Information"}},
            {CodeEnum.General, new CodeType {Code="480", DisplayName="General"}},
            {CodeEnum.OpeningDisclaimer, new CodeType {Code="490", DisplayName="Opening Disclaimer"}},
            {CodeEnum.AboutThisMedication, new CodeType {Code="360   ", DisplayName="About This Medication"}},
            {CodeEnum.WhatTheMedicationIsUsedFor, new CodeType {Code="360-10", DisplayName="What The Medication Is Used For"}},
            {CodeEnum.WhatItDoes, new CodeType {Code="360-20", DisplayName="What It Does"}},
            {CodeEnum.WhenItShouldNotBeUsed, new CodeType {Code="360-30", DisplayName="When It Should Not Be Used"}},
            {CodeEnum.WhatTheMedicinalIngredientIs, new CodeType {Code="360-40", DisplayName="What The Medicinal Ingredient Is"}},
            {CodeEnum.WhatTheImportantNonmedicinalIngredientsAre, new CodeType {Code="360-50", DisplayName="What The Important Nonmedicinal Ingredients Are"}},
            {CodeEnum.WhatDosageFormsItComesIn, new CodeType {Code="360-60", DisplayName="What Dosage Forms It Comes In"}},
            {CodeEnum.WarningAndPrecaution, new CodeType {Code="370", DisplayName="Warnings and Precautions"}},
            {CodeEnum.InteractionsWithThisMedication, new CodeType {Code="380", DisplayName="Interactions With This Medication"}},
            {CodeEnum.ProperUseOfThisMedication, new CodeType {Code="390", DisplayName="Proper use of this medication"}},
            {CodeEnum.UsualDose, new CodeType {Code="390-10", DisplayName="Usual dose"}},
            {CodeEnum.Overdose, new CodeType {Code="390-20", DisplayName="Overdose"}},
            {CodeEnum.MissedDose, new CodeType {Code="390-30", DisplayName="Missed Dose"}},
            {CodeEnum.SideEffectsandwhatToDoAboutThem, new CodeType {Code="400", DisplayName="Side effects and what to do about them"}},
            {CodeEnum.HowToStoreIt, new CodeType {Code="410", DisplayName="How to store it"}},
            {CodeEnum.ReportingSuspectedSideEffects, new CodeType {Code="420", DisplayName="Reporting suspected side effects"}},
            {CodeEnum.MoreInformation,  new CodeType {Code="430", DisplayName="More information"}},
            {CodeEnum.PartIIIRevisionDate, new CodeType {Code="470", DisplayName="Part 3 Revision Date" }},
            {CodeEnum.SchedulingSymbol, new CodeType {Code="60", DisplayName="Scheduling Symbol" }},
            {CodeEnum.IndicationsAndClinicalUse, new CodeType {Code="190", DisplayName="Indications And Clinical Use" }},
            {CodeEnum.PatientSubsets, new CodeType {Code = "190-10", DisplayName="Patient Subsets" }},
            {CodeEnum.Geriatrics, new CodeType {Code = "190-10-10", DisplayName="Geriatrics" }},
            {CodeEnum.Pediatrics, new CodeType {Code = "190-10-20", DisplayName="Pediatrics" }},
            {CodeEnum.WarningsAndPrecautions, new CodeType {Code = "210", DisplayName="Warnings And Precautions" }},
            {CodeEnum.WarningsAndPrecautionsGeneral, new CodeType {Code = "210-10", DisplayName="General" }},
            {CodeEnum.CarcinogenesisAndMutagenesis, new CodeType {Code = "210-20", DisplayName="Carcinogenesis And Mutagenesis" }},
            {CodeEnum.Cardiovascular, new CodeType {Code = "210-30", DisplayName="Cardiovascular" }},
            {CodeEnum.SpecialPopulations, new CodeType {Code = "210-210", DisplayName="Special Populations" }},
            {CodeEnum.PregnantWomen, new CodeType {Code = "210-210-10", DisplayName="Pregnant Women" }},
            {CodeEnum.NursingWomen, new CodeType {Code = "210-210-20", DisplayName="Nursing Women" }},
            {CodeEnum.SpecialPopulationsPediatrics, new CodeType {Code = "210-210-30", DisplayName="Pediatrics" }},
            {CodeEnum.SpecialPopulationsGeriatrics, new CodeType {Code = "210-210-40", DisplayName="Geriatrics" }},
            {CodeEnum.SpecialPopulationsMisc, new CodeType {Code = "210-220", DisplayName="Special Populations - Misc." }},
            {CodeEnum.MonitoringAndLaboratoryTests, new CodeType {Code = "210-230", DisplayName="Monitoring And Laboratory Tests" }}
        };      
    }

}